myfirstbolg/asiblog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from . import views

urlpatterns = [

	#url(r'^start/$',views.startView , name ='start')
	url(r'^$',login_required(views.MainView.as_view()) , name='index'),
	url(r'^(?P<pk>[0-9]+)/edit/$',login_required(views.PostUpdate.as_view()),name='edit'),
	url(r'^(?P<pk>[0-9]+)/delete/$',login_required(views.SoftDelete.as_view()),name='delete'),
	url(r'^add/$',views.PostCreat.as_view(),name='addPost'),	
]

myfirstbolg/myfirstbolg/local/urls.py
/home/ajl1079/Blog/myfirstbolg/myfirstbolg/urls.py

myfirstbolg/myfirstbolg/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.auth.urls 
from django.contrib.auth.views import login
from django.contrib.auth import views as auth_views
from asiblog.views import Register_success, Register_user
from asiblog.api import PostResource

post_resource = PostResource()

urlpatterns = [
	url(r'^asiblog/', include('asiblog.urls',namespace="asiblog")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', "asiblog.views.login"),
    url(r'^accounts/auth_view/$',"asiblog.views.auth_view"),
    url(r'^accounts/logout/$',"asiblog.views.logoutme"), 
    url(r'^accounts/register/$',Register_user.as_view()),
    url(r'^account/register_success/$',Register_success.as_view()),
    url(r'^api/', include(post_resource.urls)),
    #url('^', include('django.contrib.auth.urls'))
]

myfirstbolg/asiblog/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

class Post(models.Model):
	
    title = models.CharField(max_length=200)
    body = models.TextField()
     
    publish = models.BooleanField(default=True)          #for soft delete
    created = models.DateField(auto_now_add=True)
    modified = models.DateField(auto_now=True)      # see what to do
    user = models.ForeignKey(User,default= )

    def __unicode__(self):
        return '%s' % self.title
    
class Tag(models.Model):
    slug = models.SlugField(max_length=200)
    post = models.ManyToManyField(Post)

myfirstbolg/asiblog/views.py
from django.shortcuts import get_object_or_404, render ,render_to_response
from django.views import generic
from . import models
from models import Post
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from .form import loginForm , RegistrationForm
import datetime
from django.utils import timezone
from django.views.generic.edit import CreateView,FormView
from django.views.generic.edit import UpdateView
from django.views.generic import DetailView ,View , TemplateView
from django.contrib.auth import authenticate, login , logout
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.core.context_processors import csrf

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# class StartView(FormView):
# 	form_class="loginForm"
# 	template_name=start.html
# 	success_url='/asiblog/'

def login(request):
	c = {}
	c.update(csrf(request))
	return render_to_response('asiblog/login.html',c)

def auth_view(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username=username,password=password)
	if user is not None:
		return HttpResponseRedirect('/asiblog')
	else:
		return render(request, 'asiblog/login.html', {
            'error_message': "Wrong user name or password. Please try again",
        })
    
def logoutme(request):
	logout(request)
	return HttpResponseRedirect('/accounts/login')

class Register_user(FormView):
	# import pdb
	# pdb.set_trace()
	form_class = RegistrationForm
	model = User
	template_name = 'asiblog/register_user.html'
	#fields = ['username','email','password1','password2']
	success_url = "/account/register_success/"

	def form_valid(self,form):
		form.save()
		return super(Register_user, self).form_valid(form)

#def Register_user(request):


class Register_success(TemplateView):
	template_name = 'asiblog/register_success.html'

# class LoginRequiredMixin(object):
#     @classmethod
#     def as_view(cls, **initkwargs):
#         view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
#         return view

class MainView(generic.ListView):
	context_object_name='postset'
	template_name = 'asiblog/mainview.html'	
	paginate_by = 2

	def get_queryset(self):
		allPost=Post.objects.order_by('-created')[:]
		presentPost=[]
		for post in allPost:
			if post.publish:
				presentPost.append(post)
		return presentPost
	# @method_decorator(login_required)
 #    def dispatch(self, *args, **kwargs):
 #        return super(ProtectedView, self).dispatch(*args, **kwargs)
	
# def addPost(request):
# 	if request.method == 'POST':
# 		form = newPostForm(request.POST)
# 		if form.is_valid():
# 			p=Post(title=form.cleaned_data['title'],body=form.cleaned_data['body'])
# 			p.save()
# 			return HttpResponseRedirect(reverse('asiblog:index'))
# 	else:
# 		form = newPostForm()
			
# 	return render(request, 'asiblog/addPost.html',{'form': form})

class PostCreat(CreateView):
	
	model=Post
	template_name= 'asiblog/addPost.html'
	
	fields = ['title','body']
	success_url = '/asiblog/'
	

# def edit(request,post_id):
	
# 	if request.method == 'POST':
		
# 		form = newPostForm(request.POST)
# 		if form.is_valid():
			
# 			p = Post.objects.get(pk=post_id)
# 			p.title = form.cleaned_data['title']
# 			p.body =  form.cleaned_data['body']
# 			#p.modified = models.DateField(auto_now=True)
# 			p.save()
# 			return HttpResponseRedirect(reverse('asiblog:index'))
# 	else : 
# 		# form = newPostForm()
# 		p = Post.objects.get(pk=post_id)

# 		# form.fields['title'].initial = p.title 
# 		# form.fields['body'].initial = p.body
# 		form = newPostForm(initial={'title':p.title,'body':p.body})

# 	return render(request, 'asiblog/addPost.html',{'form': form})

class PostUpdate(UpdateView):
	# import pdb
	# pdb.set_trace()

	model = Post
	fields = ['title','body']
	#fields="__all__"
	template_name= 'asiblog/addPost.html'
	success_url = '/asiblog/'

# def delete(request,post_id):
# 	p= get_object_or_404(Post,pk=post_id);
	
# 	p.publish=False
# 	p.save()
# 	return HttpResponseRedirect(reverse('asiblog:index'))
# 	#return HttpResponseRedirect("/asiblog/")

class SoftDelete(View):
	def get(self,request,*args, **kwargs):
		p= get_object_or_404(Post,pk=kwargs['pk']);
	 	p.publish=False
	 	p.save()
	 	return HttpResponseRedirect(reverse('asiblog:index'))

myfirstbolg/asiblog/templates/asiblog/addPost.html
<h3>Enter details or edit</h3>

<form action="" method="post">
{% csrf_token %}
	{{form.title.label_tag}}
	{{form.title}}
	<br><br>
	
	{{form.body.label_tag}}
	<br>
	{{form.body}}
	<br><br>
	
<input type="submit" value="Add Post" align="center">
</form>
<button  id="myButton"  >Cancle</button>
<script type="text/javascript">
    document.getElementById("myButton").onclick = function () {
        location.href = "/asiblog/";
    };
</script>

myfirstbolg/asiblog/templates/asiblog/login.html
<h1 align="center" style="color:#0000FF">Welcone to my first blog </h1>
{%if error_message %}
<p ><b> {{error_message}} </b></p>
{% endif %}
<p>If you already have account then Login</p>
<form action="/accounts/auth_view/" method="post">
{% csrf_token %}
Username:
<input type="text" name="username">
<br><br>
Password:
<input type="password" name="password">
<br><br>
<input type="submit" value="Login">
</form>
<p>If you do not have an account please <a href="/accounts/register/ " > Sign Up first</a></p>

myfirstbolg/asiblog/templates/asiblog/mainview.html
<h1 align="center" style="color:#0000FF">Welcone to my first blog </h1>
<button  id="myButton"  >Logout</button><br><br>

<a href= "/asiblog/add"> <b>Add Post</b> </a>
<hr>
{% if postset %}

	{% for post in postset %}
		{% if post.publish %}
		<div>

		{% block title %} <b>{{post.title}}</b><br> <br> {% endblock %}
		{% block content %} {{ post.body }} {% endblock %}
			<ul>
			<li> <p>Publish Date -> {{post.created}} </p></li>
			<li> <p>Last Modified Date->{{post.modified}}</li>
			</ul>
			<h3><b>Tags</b> </h3>
			{%for tag in post.tag_set.all%}

			<p><a href="{{tag.slug}}">{{tag.slug}}</a></p>
			{% endfor %}
			
			<a href= "/asiblog/{{post.id}}/delete"><b>Delete Post</b></a><br>
			<a href= "/asiblog/{{post.id}}/edit/"><b>Edit Post</b></a>

			<hr>
		</div>
		{% endif %}
 	{% endfor %}
{% else %}
 	<p>No Post are available.</p>
{% endif %}

 {% if is_paginated %}
        <div class="pagination" align="center">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
   
{% else %}
    
    <p>No more page_obj :(</p>
{% endif %}
 
 <script type="text/javascript">
    document.getElementById("myButton").onclick = function () {
        location.href = "/accounts/logout/";
    };
</script>

myfirstbolg/asiblog/templates/asiblog/register_success.html
<h2>You have registered :) </h2>

<p>click <a href ="/accounts/login/">here </a> to login </p>

myfirstbolg/asiblog/templates/asiblog/register_user.html
<h1 align="center" style="color:#0000FF"> Welcome to Registration page </h1>

<form action="" method="post">
	{% csrf_token %}
	{{form.as_p}}
	<br><br>
	<input type="submit" value="Submit" align="center">

</form>